#!/usr/bin/env bash

###################################
# URLencodes a given input string #
###################################

if [[ -z "$1" ]]; then
    echo "Usage: urlencode <string>"
    exit 1;
fi

function urlencode() {
    old_lc_collate=$LC_COLLATE
    LC_COLLATE=C
    
    local length="${#1}"
    for (( i = 0; i < length; i++ )); do
        local c="${1:i:1}"
        case $c in
            [a-zA-Z0-9.~_-]) printf "$c" ;;
            *) printf '%%%02X' "'$c" ;;
        esac
    done
    
    LC_COLLATE=$old_lc_collate
}

echo $(urlencode $1)